config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show' 

  get 'angular-items', to: 'portfolios#angular'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

   resources :blogs do
    member do
      get :toggle_status
    end 
   end
  root to: 'pages#home'
  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies 
	accepts_nested_attributes_for :technologies,
	                  reject_if: lambda { |attrs| attrs['name'].blank?  }
	include Placeholder
	validates_presence_of :title, :body, :main_image, :thumb_image

	def self.angular
		where(subtitle: 'Angular')
	end	

	scope :ruby_on_rails_portfolio_items, -> {where(subtitle: 'Ruby on Rails') }

	after_initialize :set_defaults

	def set_defaults	
		self.main_image ||= Placeholder.image_generator(height: 600, width: 400)
		self.thumb_image ||= Placeholder.image_generator(height: 350, width: 200)
	end	
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit,:update,:show,:destroy]
  layout 'portfolio'
	def index
		@portfolio_items = Portfolio.all
	end	

  def angular
    @portfolio_items = Portfolio.angular
  end  

	def new
		@portfolio_item = Portfolio.new
    3.times {@portfolio_item.technologies.build}
	end	

	# POST /portfolios or /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_path, notice: "portfolio was successfully created." }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  	
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: "Portfolio was successfully updated." }
        format.json { render :show, status: :ok, location: portfolios_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end	

  def edit   
  	
    # 3.times {@portfolio_item.technologies.build}
  end

  def show


  end	

  def destroy  
    # Destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: "Portfolio item was successfully destroyed." }
      format.json { head :no_content }
    end
  end 

  private
  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name])
  end 	

  def set_portfolio_item
    # perform lookup
    @portfolio_item = Portfolio.find(params[:id])
  end  
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio_item) do |form| %>


  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>


  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
    <li>
      <%= technology_form.label :name %>
      <%= technology_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<% @portfolio_items.each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></p>
    <p><%= portfolio_item.subtitle %></p>
    <p><%= portfolio_item.body %></p>
    <p><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></p>
    <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
    <%= link_to "Delete", portfolio_path(portfolio_item.id), method: :delete, data: { confirm: "Are you sure"}  %>
<% end %>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create a new Portfolio", new_portfolio_path %>
<% @portfolio_items.each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></p>
    <p><%= portfolio_item.subtitle %></p>
    <p><%= portfolio_item.body %></p>
    <p><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></p>
    <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
    <%= link_to "Delete", portfolio_path(portfolio_item.id), method: :delete, data: { confirm: "Are you sure"}  %>
<% end %>

app/views/portfolios/edit.html.erb
 <h1>Edit Portfolio Item</h1>
<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h1>All Portfolio Items</h1>

<%= link_to "Create a new Portfolio", new_portfolio_path %>
<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio Item</h1>
<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<h1><%= @portfolio_item.title %><h1>
<p><%= @portfolio_item.subtitle %></p>	
<p><%= @portfolio_item.body %></p>
<p><%= image_tag @portfolio_item.main_image %></p>
<h2>Technologies used</h2>	

<% @portfolio_item.technologies.each do |technology| %>
    <p><%= technology.name %></p>
<% end %>